# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 05:58
from __future__ import unicode_literals

import blog.fields
import blog.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160808_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number1',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number2',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=blog.fields.PhoneNumberField(max_length=20, validators=[blog.validators.phone_number_validator, blog.validators.phone_number_validator, blog.validators.phone_number_validator]),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=blog.fields.ZipCodeField(default=0, max_length=5, validators=[blog.validators.zip_code_validator, blog.validators.zip_code_check, blog.validators.zip_code_validator, blog.validators.zip_code_check, blog.validators.zip_code_validator, blog.validators.zip_code_check]),
        ),
    ]
