# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketmon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='level',
            new_name='attack',
        ),
        migrations.RemoveField(
            model_name='user',
            name='catch_place',
        ),
        migrations.RemoveField(
            model_name='user',
            name='catch_pokemon',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='capture',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketmon.Pokemon'),
        ),
        migrations.AddField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketmon.User'),
        ),
    ]
