# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketmon', '0002_auto_20160725_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lnglat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=1, max_length=2)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='capture',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketmon.Location'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poketmon.Trainer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
