# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poketmon', '0003_auto_20160727_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='user',
            new_name='trainer',
        ),
    ]
