# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketmon', '0004_auto_20160727_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
