# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketmon', '0005_auto_20160727_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lnglat',
        ),
        migrations.AddField(
            model_name='location',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
